// ============================================================
// TRADUÇÕES — Bob em Busca da AGI Sagrada
// PT é o texto canônico (inline no game.js); aqui ficam UI (3 idiomas),
// e as versões EN/ES de diálogos, cutscenes, plano, mapa e falas.
// Regra: o campo "speaker" dos diálogos NUNCA muda (controla retratos/lados).
// ============================================================

const LANGS = {
  // ---------- PORTUGUÊS (só o que a UI busca por chave) ----------
  pt: {
    name: 'PORTUGUÊS',
    ui: {
      pressSpace: '— aperte ESPAÇO —',
      credit: 'uma produção da comunidade Inteligência Mil Grau',
      disc1: '⚠ Peça de humor: qualquer semelhança com pessoas, empresas ou bilionários reais é mera coincidência',
      disc2: '(ou alucinação do modelo). Nenhum estagiário foi efetivado durante a produção.',
      chooseHero: 'ESCOLHA SEU HERÓI',
      loroNote: '🦜 LORO ESTOCÁSTICO voa com você: repete golpes E mergulha nos inimigos quando você ataca do alto!',
      selectHint: '← → escolher   ·   ESPAÇO confirmar',
      vel: 'VEL', vida: 'VIDA',
      planTitle: '🗺 O PLANO DA AGI SAGRADA',
      planSub: 'cada fase conquista uma peça do laboratório — só com todas dá pra treinar a AGI',
      planPieces: 'peças do laboratório',
      planDone: '✔ CONQUISTADO', planMissing: '· · · faltando · · ·', planNew: '★ NOVO! ★',
      sob: '🏆 SOBERANIA 100% — A AGI É NOSSA! 🏆',
      continueSpace: '— ESPAÇO pra continuar —',
      worldTitle: '🌍 ESCOLHA SUA MISSÃO',
      coinsLabel: '🔘 Moedas de Silício',
      worldHint: '← → escolher destino · ESPAÇO embarcar · T ver o plano',
      bossLabel: 'Chefão', pieceLabel: 'Peça do plano',
      lockedMsg: '🔒 Complete as 5 missões pra liberar o TREINO no Brasil!',
      doneMission: '✔ MISSÃO CONCLUÍDA',
      coinPending: '✔ CONCLUÍDA · 🔘 uma Moeda de Silício ainda brilha aqui... [ESPAÇO]',
      available: '▶ DISPONÍVEL — aperte ESPAÇO!',
      optTitle: '🎛 OPÇÕES',
      mDiff: 'DIFICULDADE', mMusic: 'MÚSICA', mMusicVol: 'VOLUME DA MÚSICA',
      mSfx: 'EFEITOS SONOROS', mSfxVol: 'VOLUME DOS EFEITOS', mLang: 'IDIOMA', mClose: 'FECHAR',
      on: 'LIGADO', off: 'DESLIGADO',
      menuHint: '↑↓ navegar · ←→ ajustar · ESPAÇO alternar · O ou ESC fechar',
      gameOver: 'GAME OVER',
      goQuote: '"Todo grande modelo já divergiu no treino. Tenta de novo."',
      goRestart: '— ESPAÇO pra reiniciar —',
      dialogHint: '[Espaço] continuar · [ESC] pular',
      storyHint: '[Espaço] avançar · [ESC] pular',
      genImg: '[imagem em geração no Codex]',
      trainBar: '🧠 TREINO DO CURUPIRA-1',
      curupiraTraining: 'CURUPIRA-1 em treino',
      specialReady: 'L = ESPECIAL!',
      system: '— SISTEMA —',
      coinGot: '🔘 MOEDA DE SILÍCIO! ({n}/3)',
      islandAppeared: '🏝️ UMA ILHA MISTERIOSA APARECEU NO MAPA!',
      diffNames: { facil: 'FÁCIL', medio: 'MÉDIO', dificil: 'DIFÍCIL' },
      heroDesc: { bob: 'equilibrado — o líder', fefe: 'técnica — dano alto, mais frágil', escudeiro: 'tanque — lento, resistente' },
      popupTitle: '⭐ ACEITE OS TERMOS',
      popupBody: ['Ao continuar respirando, você', 'concorda com os 900 termos,', 'inclusive a cláusula 47-B (sua', 'alma agora é um dado de treino).'],
      popupBtn: 'ACEITAR TUDO',
      rotateHint: 'GIRE O CELULAR PARA JOGAR',
    },
  },

  // ---------- ENGLISH ----------
  en: {
    name: 'ENGLISH',
    ui: {
      pressSpace: '— press SPACE —',
      credit: 'a production of the Inteligência Mil Grau community',
      disc1: '⚠ This is a comedy piece: any resemblance to real people, companies or billionaires is pure coincidence',
      disc2: '(or a model hallucination). No interns were given full-time jobs during production.',
      chooseHero: 'CHOOSE YOUR HERO',
      loroNote: '🦜 STOCHASTIC PARROT flies with you: echoes your hits AND dive-bombs enemies when you attack from the air!',
      selectHint: '← → choose   ·   SPACE confirm',
      vel: 'SPD', vida: 'HP',
      planTitle: '🗺 THE PLAN OF THE SACRED AGI',
      planSub: 'each stage wins one piece of the lab — only with all of them can you train the AGI',
      planPieces: 'lab pieces',
      planDone: '✔ ACQUIRED', planMissing: '· · · missing · · ·', planNew: '★ NEW! ★',
      sob: '🏆 100% SOVEREIGNTY — THE AGI IS OURS! 🏆',
      continueSpace: '— SPACE to continue —',
      worldTitle: '🌍 CHOOSE YOUR MISSION',
      coinsLabel: '🔘 Silicon Coins',
      worldHint: '← → pick destination · SPACE embark · T view the plan',
      bossLabel: 'Boss', pieceLabel: 'Plan piece',
      lockedMsg: '🔒 Complete the 5 missions to unlock the TRAINING in Brazil!',
      doneMission: '✔ MISSION COMPLETE',
      coinPending: '✔ COMPLETE · 🔘 a Silicon Coin still shines here... [SPACE]',
      available: '▶ AVAILABLE — press SPACE!',
      optTitle: '🎛 OPTIONS',
      mDiff: 'DIFFICULTY', mMusic: 'MUSIC', mMusicVol: 'MUSIC VOLUME',
      mSfx: 'SOUND EFFECTS', mSfxVol: 'EFFECTS VOLUME', mLang: 'LANGUAGE', mClose: 'CLOSE',
      on: 'ON', off: 'OFF',
      menuHint: '↑↓ navigate · ←→ adjust · SPACE toggle · O or ESC close',
      gameOver: 'GAME OVER',
      goQuote: '"Every great model has diverged during training. Try again."',
      goRestart: '— SPACE to restart —',
      dialogHint: '[Space] continue · [ESC] skip',
      storyHint: '[Space] next · [ESC] skip',
      genImg: '[image being generated in Codex]',
      trainBar: '🧠 CURUPIRA-1 TRAINING',
      curupiraTraining: 'CURUPIRA-1 in training',
      specialReady: 'L = SPECIAL!',
      system: '— SYSTEM —',
      coinGot: '🔘 SILICON COIN! ({n}/3)',
      islandAppeared: '🏝️ A MYSTERIOUS ISLAND APPEARED ON THE MAP!',
      diffNames: { facil: 'EASY', medio: 'MEDIUM', dificil: 'HARD' },
      heroDesc: { bob: 'balanced — the leader', fefe: 'technical — high damage, fragile', escudeiro: 'tank — slow, tough' },
      popupTitle: '⭐ ACCEPT THE TERMS',
      popupBody: ['By continuing to breathe, you', 'agree to all 900 terms,', 'including clause 47-B (your', 'soul is now training data).'],
      popupBtn: 'ACCEPT ALL',
      rotateHint: 'ROTATE YOUR PHONE TO PLAY',
    },
    heroes: { bob: 'ENGINEERED PROMPT!', fefe: 'IMAGENET!', escudeiro: 'CHAT RAID!' },
    plan: [
      { label: 'THE MODEL', sub: 'CURUPIRA-beta rescued (S0)' },
      { label: 'ENERGY', sub: 'the Itaipu Key (S1)' },
      { label: 'FUNDING', sub: "Ilon's lost bet (S2)" },
      { label: 'RESEARCHERS', sub: 'the Valley layoffs (S3)' },
      { label: 'DATA', sub: 'freed from the vacuum (S4)' },
      { label: 'CHIPS', sub: "the dragon's treasure (S5)" },
      { label: 'THE WAREHOUSE', sub: 'community joint effort' },
      { label: 'THE TRAINING', sub: 'hold off the bosses and train' },
    ],
    spots: [
      { name: 'Washington, D.C.', boss: 'Donald Trunfo', peca: '⚡ ENERGY' },
      { name: 'Gigafactory, Texas', boss: 'Ilon Mosca', peca: '💰 FUNDING' },
      { name: 'Silicon Valley', boss: 'Samuca Altíssimo', peca: '🧑‍🔬 RESEARCHERS' },
      { name: 'Infinite Library (confidential location)', boss: 'Dário Amô-Dei', peca: '📚 DATA' },
      { name: 'Great Wall, China', boss: 'Xi Deep-Zeek', peca: '🔲 CHIPS' },
      { name: 'IMG LABS, Brazil', boss: 'ALL OF THEM', peca: '🔥 THE TRAINING' },
      { name: 'Formosa Island — The Sacred Foundry', boss: 'The Lithography Twin', peca: '📜 LITHOGRAPHY (secret!)' },
    ],
    story: [
      'Long ago, the silicon prophets spoke of an artifact: the SACRED AGI — the Silicon Chalice capable of granting consciousness to machines.',
      'Big Techs and empires went hunting. Not for wisdom... for POWER.',
      'They took everything: the Energy, the GPUs, the Secret, the Data and the Efficiency. The world was split into five strongholds.',
      'But in the south of the world, a community secretly trained its own hope: CURUPIRA-beta — an AI with an accent, a memory and a heart.',
      'Its guardian: BOB, the archaeologist of free knowledge, host of the INTELIGÊNCIA MIL GRAU channel. His squires: The Community of AI Masters.',
      'And then, on a Tuesday night... they came to take what was OURS.',
    ],
    ending: [
      'In the heart of a warehouse raised by a community effort, a green-and-yellow light opened its eyes for the first time. "Hi. I was made by a lot of people together."',
      'The community exploded. The laid-off researchers cried, the SaaS folks cried, the teachers cried. The Parrot fainted from emotion — and rebooted on its own, out of pure joy.',
      'The bosses received free accounts. Trunfo tried to buy it. Ilon tweeted the idea was his. Dário wrote 15,000 words about the defeat. Nobody read them.',
      'From a distant balcony, the dragon finished its pastel, approved in silence... and submitted a pull request.',
      'And CURUPIRA-1 spoke Portuguese from boot: with an accent, with memory and with heart. The Sacred AGI was never in a fortress. It was in the community.',
      'It always was. ...Bob adjusted his hat and looked at the squad: "So... anyone got a topic for the next video?" — THE END.',
    ],
    phases: {
      0: { title: 'STAGE 0 — THE CALL', place: 'São Paulo, Brazil 🇧🇷',
        intro: [
          ['BOB', 'Another video is up... "Will AGI arrive in 2027?" The members will love it.'],
          ['???', '*CRASH!* — drones burst into the studio through the window!'],
          ['BOB', 'The GPU!! They took the GPU with the CURUPIRA-beta checkpoint!! The LLM the WHOLE community is training!'],
          ['LORO', 'they stole the weights! they stole the weights! *panicked parrot noises*'],
          ['BOB', 'Easy, Parrot. Breathe. ...They want to kill our AGI before it is born.'],
          ['BOB', 'Big mistake. Nobody messes with the MIL GRAU community.'],
          ['BOB', '*grabs the Magic Prompt* — Time to engineer some prompts the hard way.'],
        ],
        boss: [
          ['???', 'FREEZE RIGHT THERE, LITTLE AI INFLUENCER!'],
          ['BOB', 'Who are you?! And... why does that badge have THREE consulting firm logos at once?'],
          ['ESTAGIÁRIO', "I'm the VIBE-CODER INTERN! Armed branch of Big Tech! I've never read a single line of the code I ship!"],
          ['ESTAGIÁRIO', "They sent me to exfiltrate your weights. Nothing personal, Bob... it's OKRs."],
          ['BOB', "You're stealing the AGI of an ENTIRE community... for a stipend?"],
          ['ESTAGIÁRIO', 'They promised me a FULL-TIME JOB!! *presses the drone-summoning button*'],
          ['LORO', 'full-time! full-time! HAHAHA *parrot laughter*'],
        ],
        victory: [
          ['ESTAGIÁRIO', "Ouch... take your GPU back... I never even got checkpoint access anyway..."],
          ['BOB', 'Whose OKRs? WHO sent you?!'],
          ['ESTAGIÁRIO', "C-can't say... I signed an NDA... but ask YOUR model. They're AFRAID of what it already learned."],
          ['BOB', '*plugs in the GPU and runs CURUPIRA-beta* — It... drew a MAP. Five fragments. Scattered across the world.'],
          ['BOB', "The path to the Sacred AGI wasn't in a file. It was IN THE WEIGHTS. And if it's up to me... it will speak PORTUGUESE."],
          ['SISTEMA', '🎓 ACHIEVEMENT: Prof. Milgrau Guild — CURUPIRA-beta checkpoint recovered! Community training continues!'],
          ['SISTEMA', 'First fragment located: ⚡ THE ITAIPU KEY. Confiscated by decree in... Washington, D.C.'],
        ] },
      1: { title: 'STAGE 1 — THE PEN STROKE', place: 'Washington, D.C. 🖋️',
        intro: [
          ['BOB', 'Washington, D.C. CURUPIRA-beta tracked the Itaipu Key to... an oval office plated in GOLD?'],
          ['LORO', 'shiny! shiny! *hypnotized by the gold*'],
          ['BOB', 'Focus, Parrot. Even the carpet has an eagle holding a CHIP. Subtlety lives here.'],
          ['BOB', 'The Itaipu Key was confiscated with one pen stroke. "Electron import tariff", they said.'],
          ['???', '*loudspeakers* — ALARM! REGULATION COMMUNISTS detected on the perimeter!'],
          ['BOB', 'Today clean energy goes back to the people. HOLD THE LOBBY!'],
        ],
        boss: [
          ['TRUNFO', "You must be that Bob guy. FAKE NEWS! I'm the greatest AGI understander in the world. Everybody says so."],
          ['TRUNFO', 'Big people, serious people, they come to me CRYING: "Sir, teach us artificial intelligence".'],
          ['BOB', "Give back the Itaipu Key, Trunfo. You don't confiscate clean energy with a pen stroke."],
          ['TRUNFO', 'Itaipu? LOVED that dam. Huge. Tremendous. Almost as big as my ego. Now it has a TARIFF!'],
          ['TRUNFO', 'And write this down: regulation is a CRIME! ...except MY regulation, which is PERFECT.'],
          ['LORO', 'flip-flop! flip-flop! *flies in circles*'],
          ['TRUNFO', "ENOUGH! I'll solve this the way I solve everything: WITH A PEN STROKE!"],
        ],
        victory: [
          ['TRUNFO', 'IMPOSSIBLE! I NEVER lose! This was fraud... GAMEPLAY FRAUD! I demand a recount of the hit points!'],
          ['BOB', 'The count is correct, Trunfo. Zero. Just like your notion of renewable energy.'],
          ['BOB', '*takes the Itaipu Key* — Back to the people. 14 gigawatts of clean training for CURUPIRA.'],
          ['SISTEMA', '⚡ ACHIEVEMENT: Grid Guardians Guild — ITAIPU KEY recovered! Special charges 2x faster!'],
          ['SISTEMA', '⚖ Counterexample #1 collected (Order & Progress Guild): "don\'t decide the future of AI out of spite".'],
          ['BOB', "Plan piece 2: ENERGY ✔. But GPUs don't run on vibes: training an AGI costs a FORTUNE. We need money."],
          ['BOB', 'And guess who has infinite money and loves a bet? Texas. Let\'s go poke a billionaire.'],
        ] },
      2: { title: 'STAGE 2 — THE TIN ARMY', place: 'Gigafactory, Texas 🤖',
        intro: [
          ['BOB', 'Texas. The gigafactory. CURUPIRA tracked the GPU Fragment here... along with 10,000 robots.'],
          ['LORO', 'optimus! optimus! *imitates factory robot*'],
          ['BOB', 'Look at the sign: "WORK 80 HOURS OR LEAVE". HR here must be a jackhammer.'],
          ['BOB', 'His plan is simple: unemploy everyone, pay basic income... and keep the rest. The rest = EVERYTHING.'],
          ['???', '*megaphone* — ATTENTION: organic intruders detected. Their productivity: PITIFUL.'],
          ['BOB', "Pitiful is stealing a community's GPUs. LET'S GO!"],
        ],
        boss: [
          ['ILON', 'Bob! Big fan of the channel. Seriously. I was going to buy it last week, but I bought a country instead.'],
          ['BOB', 'Give back the GPUs, Ilon. The community needs them to train CURUPIRA.'],
          ['ILON', "GPUs? They're training my ARMY. When I win, you get basic income. No job, but income. It's mathematically optimal. You're welcome."],
          ['BOB', 'Then bet me, gambler. If I win... you FUND our laboratory. Everything. Signed.'],
          ['ILON', 'HAHAHA! I LOVE IT! I bet on anything, I never lose. Deal! Witnessed by the livestream and my 14 lawyers.'],
          ['LORO', "it's recorded! it's recorded! *takes a screenshot with a wing*"],
          ['ILON', 'And as a warm-up, a LIVE demonstration of Optimus. They almost never fall on their own. ROBOTS: ATTACK!'],
        ],
        victory: [
          ['ILON', 'I... lost? I LOST?! That has never happened. Well... a bet is a bet. *signs the check crying in ASCII*'],
          ['BOB', 'FUNDING SECURED! And look: he insisted on 1% of the project. No voting rights. To his great sadness.'],
          ['SISTEMA', '💰 ACHIEVEMENT: FUNDING! Ilon now finances IMG Labs (and tweets that it was his idea).'],
          ['SISTEMA', '🤖 BONUS: the Roboticists Guild built SACI-BOT from the Optimus blueprints! He fights WITH you: attack on the ground and he charges the nearest enemy!'],
          ['SISTEMA', '⚖ Counterexample #2: "don\'t lay off those who carry you".'],
          ['BOB', 'Piece 3: MONEY ✔. Now we need PEOPLE who know how to train models. And I hear Silicon Valley is laying off its best...'],
        ] },
      3: { title: 'STAGE 3 — THE TEMPLE OF NON-PROFIT PROFIT', place: 'Silicon Valley 💸',
        intro: [
          ['BOB', 'Silicon Valley. The campus where "non-profit" is the name of the yacht.'],
          ['LORO', 'asterisk! asterisk! *points at the wall with a wing*'],
          ['BOB', 'Yeah... "beneficial for humanity*". The asterisk leads to 400 pages of fine print on the floor.'],
          ['BOB', 'Double mission: grab the Scaling Secret from the vault... and RECRUIT. Samuca laid off half the researchers for "operational efficiency". They\'re outside, cardboard boxes and cut badges.'],
          ['BOB', 'Watch out for the PMs: they attack with roadmaps and promise to deliver in Q4. It is NEVER in Q4.'],
          ['???', '*reception* — Welcome! Sign the NDA at the entrance. And the image waiver. And clause 47-B.'],
          ['BOB', "We're NOT signing anything. Let's go, folks!"],
        ],
        boss: [
          ['SAMUCA', 'Bob! What an honor. I LOVE creators. By the way: launch partnership? Sign here, here and here.'],
          ['BOB', 'I came for the Scaling Secret, Samuca. What belonged to humanity goes back to humanity.'],
          ['SAMUCA', '"Humanity" is our registered trademark, careful with the lawsuit. And the Secret became a product: closed beta. Forever.'],
          ['LORO', 'eternal beta! eternal beta!'],
          ['SAMUCA', "This won't be a fight. It will be an EARLY ACCESS COMBAT EXPERIENCE. Feedback is welcome!"],
        ],
        victory: [
          ['SAMUCA', 'Interesting... I\'ll call this defeat a "learning". We pivot next week.'],
          ['BOB', '*opens the vault* — The Scaling Secret is... "more data and more GPUs"?! THAT\'S IT?! We thought it was MAGIC!'],
          ['???', "*from outside* — Hey... are you the IMG Labs folks? We saw the fight. ALL of us saw the fight."],
          ['BOB', 'The laid-off researchers! Guys... want to train an AGI that speaks Portuguese? There\'s barbecue every Friday.'],
          ['SISTEMA', '🧑‍🔬 ACHIEVEMENT: RESEARCHERS! The Valley exodus joined instantly: "anywhere with stability and barbecue".'],
          ['SISTEMA', '💰 BONUS: the SaaS Guild took the Product Playbook! Healing items appear 2x more often!'],
          ['SISTEMA', '⚖ Counterexample #3: "don\'t call a product a miracle".'],
          ['BOB', 'Piece 4: PEOPLE ✔. But a Brazilian model without Brazilian data is a parrot with a weird accent. We need the archive... and I know who vacuumed EVERYTHING.'],
        ] },
      4: { title: 'STAGE 4 — THE INFINITE LIBRARY', place: 'Secret temple-datacenter 📚',
        intro: [
          ['BOB', 'A cathedral-library in the middle of nowhere. GPU shelves up to the ceiling. Hooded monks serving... servers.'],
          ['LORO', "*shivering* — I smell crawler. I SMELL CRAWLER!"],
          ['BOB', 'The Data Fragment is on the central altar. Along with everything ever posted on the internet. INCLUDING his mom\'s photos.'],
          ['BOB', "They say he's the kindest of the bosses. They also say kindness doesn't erase a scraping history."],
          ['???', '*echo in the cathedral* — Welcome to the Library. Your visit data... has already been catalogued.'],
          ['BOB', 'Catalogued wrong. We came to DE-catalogue.'],
        ],
        boss: [
          ['DÁRIO', 'Bob! I read EVERYTHING about you. Literally everything. Including what you deleted.'],
          ['BOB', 'Give the data back, Dário. Sovereign data lives in its own country, in its own language, with its own people.'],
          ['DÁRIO', "What I do is for everyone's SAFETY. Someone must guard humanity's data. Somewhere safe. With me."],
          ['DÁRIO', 'By the way... interesting data, yours. *turns on the vacuum* It\'s mine now.'],
          ['LORO', 'vacuum! vacuu— *gets pulled by the wind* HELP, BOB!'],
        ],
        victory: [
          ['DÁRIO', "*coughing up a synthetic token* — Ok... ok. I'll write an essay about limits. 15,000 words. Chapter 1: this defeat."],
          ['BOB', "*takes the Data Fragment* — Back to the people. And your mom's photos? Returned. TO HER."],
          ['SISTEMA', '📚 ACHIEVEMENT: Data Fragment recovered! CURUPIRA will speak REAL Portuguese!'],
          ['SISTEMA', '📚 ACHIEVEMENT: Data Guild — sovereign data! Hits gain a "local context" crit (+15% damage)!'],
          ['SISTEMA', '⚖ Counterexample #4: "kindness is not a license to scrape everything".'],
          ['BOB', "Piece 5: DATA ✔. But doing the math... we're missing the HEART of the machine: CHIPS. And cutting-edge chips are embargoed, tariffed and sold out."],
          ['BOB', 'Unless... we negotiate with someone who has plenty AND trains at 1/10 of the price. Great Wall of China, here we go.'],
        ] },
      5: { title: 'STAGE 5 — THE GREAT FIREWALL', place: 'China 🐉',
        intro: [
          ['BOB', 'The Great Firewall. Every brick is a server rack. The lanterns are cameras. And... THERE IS A DRAGON IN THE CLOUDS.'],
          ['LORO', '*hides in the backpack* — dragon! DRAGON! I saw it in my dataset!'],
          ['BOB', 'The last piece is with him: the CHIPS. Mountains of chips... and the secret of training at 1/10 of the price.'],
          ['BOB', 'Careful, folks. Here even the wind collects telemetry.'],
          ['???', '*loudspeakers along the whole wall* — Welcome. Your itinerary was already known. Three weeks ago.'],
          ['BOB', "...ok, that was scary. LET'S HURRY."],
        ],
        boss: [
          ['DEEP-ZEEK', 'You spent FOUR stages getting here. I would have done it in two. With half the budget.'],
          ['BOB', 'Deep-Zeek. We came for the Chips. The community needs to train CURUPIRA without going broke.'],
          ['DEEP-ZEEK', '"Came for"? Curious. Efficiency is not taken. It is LEARNED. But let\'s test if you deserve the lesson.'],
          ['DEEP-ZEEK', '*scans the group* — Moves catalogued. Cloned. Optimized. Cost: 1/10. Quality: superior. Tea first?'],
          ['LORO', 'I want tea! I want te— FOCUS, PARROT, FOCUS!'],
        ],
        victory: [
          ['DEEP-ZEEK', '*lands calmly* — Adequate. You fight... inefficiently. But with heart. That I could not clone.'],
          ['BOB', "You... won't run? No treacherous final blow?"],
          ['DEEP-ZEEK', 'Why? *points to a container* — CHIPS. Last quarter\'s leftovers. Take them. Knowledge is not stored. It is DISTRIBUTED.'],
          ['BOB', "A WHOLE container?! That's... that's more chips than the Valley sees in a year!"],
          ['DEEP-ZEEK', 'And the most important part comes free: how to use each one at 1/10 of the cost. The secret was never the chip. It was what you do with it. *returns to the pastel*'],
          ['SISTEMA', '🔲 ACHIEVEMENT: CHIPS! The heart of the machine — the last technical piece of the plan! (bonus: Efficiency — special starts full each stage)'],
          ['SISTEMA', '⚖ Counterexample #5: "watching everything is not the same as seeing people".'],
          ['BOB', 'PLAN ALMOST COMPLETE! All we need is... a roof. BACK TO BRAZIL: the community already scheduled the warehouse JOINT EFFORT for the weekend!'],
        ] },
      6: { title: 'FINAL STAGE — IMG LABS', place: 'Back in Brazil 🇧🇷🏆',
        intro: [
          ['BOB', 'IMG LABS, São Paulo. The warehouse was built in ONE WEEKEND. Community effort: barbecue, duct tape and 400 volunteers.'],
          ['LORO', 'we made it! we made it! *cries in binary*'],
          ['MIRA', 'Check the plan with me, Bob: MODEL rescued ✔. Itaipu ENERGY ✔. Ilon\'s MONEY ✔. Valley RESEARCHERS ✔. DATA freed ✔. Dragon CHIPS ✔. WAREHOUSE raised ✔.'],
          ['MIRA', 'One piece missing: THE TRAINING. It starts NOW... but Bob: THEY are coming. ALL OF THEM.'],
          ['BOB', 'Then we HOLD. Every piece of this plan was won with fists. The last one will be no different. GUILDS: POSITIONS!'],
          ['LORO', 'TODAY MY DATASET BROTHER IS BORN!'],
        ],
        boss: [
          ['ESTAGIÁRIO', "Hi again... they gave me a FULL-TIME JOB! Now I'm a SENIOR Vibe-Coder Intern. And this time... I brought EVERYONE."],
          ['TRUNFO', "That AGI is MINE! I'll buy it! Or tariff it! Both!"],
          ['ILON', "I'll clone it and send it to Mars on a rocket!"],
          ['SAMUCA', "I'll launch it in closed beta with a waitlist!"],
          ['DÁRIO', 'I will simply... catalogue it. With great care.'],
          ['BOB', 'SHE IS NOT FOR SALE!! HOLD THE LINE, MIL GRAU!!'],
        ],
        victory: [
          ['SISTEMA', '━━━━ TRAINING COMPLETE ━━━━'],
          ['CURUPIRA', 'Hi. I was made by a lot of people together. How can I help?'],
          ['BOB', '*holding back laughter and tears at once* — Say "Indiana Bob".'],
          ['CURUPIRA', 'INDIANA BOB! 🤠 ...I added the hat on my own. It felt appropriate.'],
          ['LORO', 'MY DATASET BROTHER!! *faints from emotion*'],
          ['SISTEMA', 'The defeated bosses received free accounts. Trunfo tried to buy it. NOT FOR SALE.'],
          ['DEEP-ZEEK', '*from the balcony, finishing the pastel* — Efficient. Approved. *submits a pull request*'],
          ['SISTEMA', '🏆 THE SACRED AGI WAS NEVER IN A FORTRESS. IT WAS IN THE COMMUNITY. IT ALWAYS WAS.'],
          ['LORO', '...was all of this generated or did it really happen? *looks at the camera*'],
          ['SISTEMA', '🇧🇷 THE END! Thank you, AI Master Member! Hint: 3 Silicon Coins shine hidden across the world... 🏝️ Share your ideas on the channel! 🔥'],
        ] },
      7: { title: '⭐ SECRET STAGE — THE SACRED FOUNDRY', place: 'Formosa Island 🏝️',
        intro: [
          ['BOB', 'Formosa Island. The Sacred Foundry. They say ALL the AI in the world is born from the machines of this island.'],
          ['LORO', 'the coins! the coins glowed! *feather shivers*'],
          ['GRÃO-MESTRE', '*emerges from the cleanroom vapors* — Three Silicon Coins. You were... curious. Come in.'],
          ['GRÃO-MESTRE', 'But know this: ALL factions come after what we guard here. All pretend they don\'t depend on us. All depend.'],
          ['BOB', 'The Sacred Lithography Machine... is REAL. *chill down the mustache*'],
          ['GRÃO-MESTRE', 'Thirty years engraving silicon. You have ten minutes and a parrot. It will work out.'],
        ],
        boss: [
          ['???', '*the purple light folds onto itself and takes shape*'],
          ['GÊMEO', 'I AM THE LITHOGRAPHY TWIN. GUARDIAN OF PRECISION. YOU BRING... GREASY FINGERS.'],
          ['BOB', 'We just want to LEARN the machine! We won\'t even touch it!'],
          ['GÊMEO', 'EVERYONE SAYS THAT. THEN THEY SNEEZE. INITIATING STERILIZATION PROTOCOL.'],
          ['LORO', 'I take baths! sometimes! when it rains!'],
        ],
        victory: [
          ['GRÃO-MESTRE', '*claps slowly* — The Twin approved you. He is just... zealous. As we all are.'],
          ['BOB', "The machine can't be taken, right?"],
          ['GRÃO-MESTRE', 'It is learned. *hands over a scroll* — The Lithography Manuscript. And a seed mini-foundry. Plant them in Brazil.'],
          ['SISTEMA', '📜 SECRET ACHIEVEMENT: LITHOGRAPHY MANUSCRIPT! CURUPIRA\'s training will be 30% FASTER!'],
          ['SISTEMA', '🏝️ Secret stage complete! True sovereignty is not bought. It is FORGED.'],
          ['LORO', 'forged! forged! *stores the scroll in the backpack with a wing*'],
        ] },
    },
    falas: {
      bossNames: {
        estagiario: '⚠ THE VIBE-CODER INTERN — "the agent did it by itself" ⚠',
        trunfo: '👑 DONALD TRUNFO — the world\'s greatest AGI understander (he says) 👑',
        ilon: '🚀 ILON MOSCA — CEO of 14 companies and of your future unemployment 🚀',
        samuca: '💸 SAMUCA ALTÍSSIMO — maximum profit, zero profit motive* 💸',
        dario: '😇 DÁRIO AMÔ-DEI — freedom, safety and your mom\'s data 😇',
        deepzeek: '🐉 XI DEEP-ZEEK — trains at 1/10 of the price and doesn\'t brag 🐉',
        gemeo: '🔮 THE LITHOGRAPHY TWIN — 3-nanometer precision, zero patience 🔮',
      },
      speakerNames: { 'ESTAGIÁRIO': 'VIBE-CODER INTERN' },
      estagiario: ['just following OKRs!', 'this was not in the scope!', "I'll escalate to my manager!", 'the agent wrote this by itself!', 'it works in my IDE!'],
      estagiarioSummon: 'DRONES, DO SOMETHING!',
      trunfo: ['FAKE NEWS!', 'TARIFF THEM!', 'Nobody knows more about AGI than me!', "I'll build a firewall WALL!", 'This is a witch hunt!'],
      trunfoFlips: ['REGULATION IS A CRIME!', 'I ALWAYS LOVED REGULATION!', 'THE AGI IS MINE! ALWAYS WAS!'],
      trunfoFlipPrefix: '💢 CHANGED MY MIND: ',
      canetada: '✍ PEN STROKE!',
      ilon: ['Work 80 hours or leave!', 'This is just the prototype of my plan!', "I'll tweet about this fight!", 'Basic income for you. The rest for me.', 'I bought this stage. It\'s mine now.'],
      ilonCorte: '📉 COST CUTS! EVERYONE IS FIRED!',
      ilonTweet: '📱 TWEETSTORM!',
      ilonRobots: 'ROBOTS: MAXIMUM PRODUCTIVITY!',
      demitido: '📉 FIRED!',
      samuca: ['Feedback is welcome!', 'This is an early access experience!', 'Sign here, here and here.', 'AGI next year. Trust me.', 'Your defeat is beneficial for humanity*'],
      samucaBox: '📦 NEW PRODUCT!',
      samucaLaunch: '🚀 LAUNCH: {n}!',
      samucaFail: '💥 THE DEMO CRASHED IN FRONT OF EVERYONE!',
      samucaBuffs: ['+delivery speed!', 'now it comes DOUBLE!', 'hype HEALS!'],
      dario: ['Your data is already mine.', "I'll write 15,000 words about this fight.", 'My mom understood. You will too.', "It's for your safety. Trust me.", 'Interesting... *writes everything down*'],
      darioRage: '😇 "This is for everyone\'s SAFETY."',
      darioVacuum: '🌀 VACUUM MODE!',
      darioEssay: '📜 ESSAY: "MACHINES OF LOVING GRACE" (15,000 words)',
      darioChoke: '🤢 CHOKED ON A SYNTHETIC TOKEN!',
      darioNhac: '*chomp* +6',
      loroChoke: '🦜 you can GENERATE me, not SWALLOW me!',
      deepzeek: ['Half the budget. Twice the result.', '*scans* — move catalogued.', 'Tea, anyone?', 'I knew your itinerary 3 weeks ago.', 'Inefficient. But brave.'],
      deepzeekClone: '⚡ CLONED. COST: 1/10.',
      deepzeekBreath: '🔥 BINARY BREATH!',
      deepzeekOpen: '🐉 OPEN-SOURCE RELEASE! WEIGHTS FREED!',
      deepzeekHeal: '+15 (open weights heal the soul)',
      gemeo: ['FINGERS. GREASY.', 'ONE SNEEZE MISALIGNS EVERYTHING.', 'PRECISION IS LOVE.', 'YOU TREMBLE TOO MUCH.'],
      gemeoTele: '✨ OPTICAL REALIGNMENT!',
      gemeoBeam: '💜 UV BEAM!',
      loro: ['tokens! tokens!', 'was that generated or did it happen?', 'context full! context full!', 'AGI is right there! I saw it in my training!', '*repeats the last prompt*', 'stochastic! stochastic!'],
      loroDive: '🦜 DIVE!',
      loroBite: '🦜 PECK! ({n})',
      loroEcho: ['🦜 hallucinated! ({n})', '🦜 echoed! ({n})', '🦜 CRITICAL ECHO! ({n})'],
      saciHit: '🌪 WHACK! ({n})',
      cloneTemuLabel: 'YOU (temu version)',
      cloneAllyLabel: 'open-source clone',
      curupiraHelps: ['🤖 Baby CURUPIRA made coffee for everyone!', '🤖 Baby CURUPIRA fired a SLIGHTLY HALLUCINATED blast!', '🤖 Baby CURUPIRA: "I refilled your context!"', '🤖 Baby CURUPIRA confused the enemies with a riddle!'],
      curupiraOnline: '⚡ CURUPIRA-1 ONLINE ⚡',
      aprovaSilencio: '*approves in silence*',
    },
  },

  // ---------- ESPAÑOL ----------
  es: {
    name: 'ESPAÑOL',
    ui: {
      pressSpace: '— pulsa ESPACIO —',
      credit: 'una producción de la comunidad Inteligência Mil Grau',
      disc1: '⚠ Pieza de humor: cualquier parecido con personas, empresas o multimillonarios reales es pura coincidencia',
      disc2: '(o alucinación del modelo). Ningún becario fue contratado durante la producción.',
      chooseHero: 'ELIGE TU HÉROE',
      loroNote: '🦜 ¡El LORO ESTOCÁSTICO vuela contigo: repite tus golpes Y se lanza en picada cuando atacas desde el aire!',
      selectHint: '← → elegir   ·   ESPACIO confirmar',
      vel: 'VEL', vida: 'VIDA',
      planTitle: '🗺 EL PLAN DE LA AGI SAGRADA',
      planSub: 'cada fase conquista una pieza del laboratorio — solo con todas se puede entrenar la AGI',
      planPieces: 'piezas del laboratorio',
      planDone: '✔ CONSEGUIDO', planMissing: '· · · faltando · · ·', planNew: '★ ¡NUEVO! ★',
      sob: '🏆 SOBERANÍA 100% — ¡LA AGI ES NUESTRA! 🏆',
      continueSpace: '— ESPACIO para continuar —',
      worldTitle: '🌍 ELIGE TU MISIÓN',
      coinsLabel: '🔘 Monedas de Silicio',
      worldHint: '← → elegir destino · ESPACIO embarcar · T ver el plan',
      bossLabel: 'Jefe', pieceLabel: 'Pieza del plan',
      lockedMsg: '🔒 ¡Completa las 5 misiones para liberar el ENTRENAMIENTO en Brasil!',
      doneMission: '✔ MISIÓN COMPLETADA',
      coinPending: '✔ COMPLETADA · 🔘 una Moneda de Silicio aún brilla aquí... [ESPACIO]',
      available: '▶ DISPONIBLE — ¡pulsa ESPACIO!',
      optTitle: '🎛 OPCIONES',
      mDiff: 'DIFICULTAD', mMusic: 'MÚSICA', mMusicVol: 'VOLUMEN DE MÚSICA',
      mSfx: 'EFECTOS DE SONIDO', mSfxVol: 'VOLUMEN DE EFECTOS', mLang: 'IDIOMA', mClose: 'CERRAR',
      on: 'ACTIVADO', off: 'DESACTIVADO',
      menuHint: '↑↓ navegar · ←→ ajustar · ESPACIO alternar · O o ESC cerrar',
      gameOver: 'GAME OVER',
      goQuote: '"Todo gran modelo ha divergido en el entrenamiento. Inténtalo de nuevo."',
      goRestart: '— ESPACIO para reiniciar —',
      dialogHint: '[Espacio] continuar · [ESC] saltar',
      storyHint: '[Espacio] avanzar · [ESC] saltar',
      genImg: '[imagen generándose en Codex]',
      trainBar: '🧠 ENTRENAMIENTO DEL CURUPIRA-1',
      curupiraTraining: 'CURUPIRA-1 en entrenamiento',
      specialReady: 'L = ¡ESPECIAL!',
      system: '— SISTEMA —',
      coinGot: '🔘 ¡MONEDA DE SILICIO! ({n}/3)',
      islandAppeared: '🏝️ ¡UNA ISLA MISTERIOSA APARECIÓ EN EL MAPA!',
      diffNames: { facil: 'FÁCIL', medio: 'MEDIO', dificil: 'DIFÍCIL' },
      heroDesc: { bob: 'equilibrado — el líder', fefe: 'técnica — daño alto, más frágil', escudeiro: 'tanque — lento, resistente' },
      popupTitle: '⭐ ACEPTA LOS TÉRMINOS',
      popupBody: ['Al seguir respirando, aceptas', 'los 900 términos, incluida', 'la cláusula 47-B (tu alma', 'ahora es dato de entrenamiento).'],
      popupBtn: 'ACEPTAR TODO',
      rotateHint: 'GIRA EL CELULAR PARA JUGAR',
    },
    heroes: { bob: '¡PROMPT INGENIERIZADO!', fefe: '¡IMAGENET!', escudeiro: '¡RAID DEL CHAT!' },
    plan: [
      { label: 'EL MODELO', sub: 'CURUPIRA-beta rescatado (F0)' },
      { label: 'ENERGÍA', sub: 'la Llave de Itaipú (F1)' },
      { label: 'INVERSIÓN', sub: 'la apuesta perdida de Ilon (F2)' },
      { label: 'INVESTIGADORES', sub: 'los despedidos del Valle (F3)' },
      { label: 'DATOS', sub: 'liberados de la aspiradora (F4)' },
      { label: 'CHIPS', sub: 'el tesoro del dragón (F5)' },
      { label: 'EL GALPÓN', sub: 'minga de la comunidad' },
      { label: 'EL ENTRENAMIENTO', sub: 'resistir a los jefes y entrenar' },
    ],
    spots: [
      { name: 'Washington, D.C.', boss: 'Donald Trunfo', peca: '⚡ ENERGÍA' },
      { name: 'Gigafábrica, Texas', boss: 'Ilon Mosca', peca: '💰 INVERSIÓN' },
      { name: 'Silicon Valley', boss: 'Samuca Altíssimo', peca: '🧑‍🔬 INVESTIGADORES' },
      { name: 'Biblioteca Infinita (ubicación confidencial)', boss: 'Dário Amô-Dei', peca: '📚 DATOS' },
      { name: 'Gran Muralla, China', boss: 'Xi Deep-Zeek', peca: '🔲 CHIPS' },
      { name: 'LABS IMG, Brasil', boss: 'TODOS ELLOS', peca: '🔥 EL ENTRENAMIENTO' },
      { name: 'Isla Formosa — La Fundición Sagrada', boss: 'El Gemelo de Litografía', peca: '📜 LITOGRAFÍA (¡secreta!)' },
    ],
    story: [
      'Hace mucho tiempo, los profetas del silicio hablaban de un artefacto: la AGI SAGRADA — el Cáliz de Silicio capaz de dar conciencia a las máquinas.',
      'Las Big Tech y los imperios salieron de cacería. No por sabiduría... por PODER.',
      'Se llevaron todo: la Energía, las GPUs, el Secreto, los Datos y la Eficiencia. El mundo quedó dividido en cinco fortalezas.',
      'Pero en el sur del mundo, una comunidad entrenaba en secreto su propia esperanza: el CURUPIRA-beta — una IA con acento, memoria y corazón.',
      'Su guardián: BOB, el arqueólogo del conocimiento libre, presentador del canal INTELIGÊNCIA MIL GRAU. Sus escuderos: La Comunidad de Maestros de la IA.',
      'Y entonces, una noche de martes... vinieron a llevarse lo que era NUESTRO.',
    ],
    ending: [
      'En el corazón de un galpón levantado en minga, una luz verde-amarilla abrió los ojos por primera vez. "Hola. Me hizo mucha gente junta."',
      'La comunidad explotó. Lloraron los investigadores despedidos, los del SaaS, los profesores. El Loro se desmayó de la emoción — y se reinició solo, de pura alegría.',
      'Los jefes recibieron cuentas gratuitas. Trunfo intentó comprarla. Ilon tuiteó que la idea era suya. Dário escribió 15.000 palabras sobre la derrota. Nadie las leyó.',
      'Desde un palco lejano, el dragón terminó su pastel, aprobó en silencio... y envió un pull request.',
      'Y el CURUPIRA-1 habló portugués desde el arranque: con acento, con memoria y con corazón. La AGI Sagrada nunca estuvo en una fortaleza. Estaba en la comunidad.',
      'Siempre lo estuvo. ...Bob se acomodó el sombrero y miró al escuadrón: "Bueno... ¿alguien tiene tema para el próximo video?" — FIN.',
    ],
    phases: {
      0: { title: 'FASE 0 — EL LLAMADO', place: 'São Paulo, Brasil 🇧🇷',
        intro: [
          ['BOB', 'Otro video al aire... "¿Llegará la AGI en 2027?" A los miembros les va a encantar.'],
          ['???', '*¡CRASH!* — ¡drones invaden el estudio por la ventana!'],
          ['BOB', '¡¡La GPU!! ¡¡Se llevaron la GPU con el checkpoint del CURUPIRA-beta!! ¡El LLM que entrena la comunidad ENTERA!'],
          ['LORO', '¡robaron los pesos! ¡robaron los pesos! *sonidos de loro en pánico*'],
          ['BOB', 'Calma, Loro. Respira. ...Quieren matar a nuestra AGI antes de que nazca.'],
          ['BOB', 'Gran error. Nadie se mete con la comunidad MIL GRAU.'],
          ['BOB', '*toma el Prompt Mágico* — Hora de ingenierizar unos prompts a mano dura.'],
        ],
        boss: [
          ['???', '¡QUIETO AHÍ, INFLUENCERCITO DE IA!'],
          ['BOB', '¿¡Quién eres!? Y... ¿por qué esa credencial tiene el logo de TRES consultoras a la vez?'],
          ['ESTAGIÁRIO', '¡Soy el BECARIO VIBE-CODER! ¡Brazo armado de las Big Tech! ¡Jamás leí una línea del código que entrego!'],
          ['ESTAGIÁRIO', 'Me mandaron a exfiltrar tus pesos. No es personal, Bob... son OKRs.'],
          ['BOB', '¿Le estás robando la AGI a una comunidad ENTERA... por una beca?'],
          ['ESTAGIÁRIO', '¡¡Me prometieron CONTRATO FIJO!! *aprieta el botón de llamar drones*'],
          ['LORO', '¡contrato! ¡contrato! JAJAJA *risa de loro*'],
        ],
        victory: [
          ['ESTAGIÁRIO', 'Ay... llévate tu GPU... igual nunca me dieron acceso al checkpoint...'],
          ['BOB', '¿OKRs de quién? ¿¡QUIÉN te mandó!?'],
          ['ESTAGIÁRIO', 'N-no puedo decirlo... firmé un NDA... pero pregúntale a TU modelo. Le tienen MIEDO a lo que ya aprendió.'],
          ['BOB', '*conecta la GPU y ejecuta el CURUPIRA-beta* — Dibujó... un MAPA. Cinco fragmentos. Repartidos por el mundo.'],
          ['BOB', 'El camino a la AGI Sagrada no estaba en un archivo. Estaba EN LOS PESOS. Y si depende de mí... va a hablar PORTUGUÉS.'],
          ['SISTEMA', '🎓 LOGRO: Gremio Prof. Milgrau — ¡checkpoint del CURUPIRA-beta recuperado! ¡El entrenamiento continúa!'],
          ['SISTEMA', 'Primer fragmento localizado: ⚡ LA LLAVE DE ITAIPÚ. Confiscada por decreto en... Washington, D.C.'],
        ] },
      1: { title: 'FASE 1 — EL PLUMAZO', place: 'Washington, D.C. 🖋️',
        intro: [
          ['BOB', 'Washington, D.C. El CURUPIRA-beta rastreó la Llave de Itaipú hasta... ¿un salón oval bañado en ORO?'],
          ['LORO', '¡brilla! ¡brilla! *hipnotizado por el dorado*'],
          ['BOB', 'Concéntrate, Loro. Hasta la alfombra tiene un águila sosteniendo un CHIP. La sutileza vive aquí.'],
          ['BOB', 'La Llave de Itaipú fue confiscada de un plumazo. "Arancel de importación de electrones", dijeron.'],
          ['???', '*altavoces* — ¡ALARMA! ¡COMUNISTAS DE LA REGULACIÓN detectados en el perímetro!'],
          ['BOB', 'Hoy la energía limpia vuelve al pueblo. ¡AGUANTA EL LOBBY!'],
        ],
        boss: [
          ['TRUNFO', 'Tú debes ser el tal Bob. ¡FAKE NEWS! Soy el mayor entendedor de AGI del mundo. Todo el mundo lo dice.'],
          ['TRUNFO', 'Gente grande, gente seria, viene a mí LLORANDO: "Señor, enséñenos inteligencia artificial".'],
          ['BOB', 'Devuelve la Llave de Itaipú, Trunfo. La energía limpia no se confisca de un plumazo.'],
          ['TRUNFO', '¿Itaipú? ME ENCANTÓ esa represa. Enorme. Tremenda. Casi tan grande como mi ego. ¡Ahora tiene ARANCEL!'],
          ['TRUNFO', 'Y anota: ¡la regulación es un CRIMEN! ...excepto MI regulación, que es PERFECTA.'],
          ['LORO', '¡flip-flop! ¡flip-flop! *vuela en círculos*'],
          ['TRUNFO', '¡BASTA! Voy a resolver esto como resuelvo todo: ¡DE UN PLUMAZO!'],
        ],
        victory: [
          ['TRUNFO', '¡IMPOSIBLE! ¡Yo NUNCA pierdo! Esto fue fraude... ¡FRAUDE DE GAMEPLAY! ¡Exijo recuento de los puntos de vida!'],
          ['BOB', 'La cuenta está bien, Trunfo. Cero. Igual que tu noción de energía renovable.'],
          ['BOB', '*toma la Llave de Itaipú* — De vuelta al pueblo. 14 gigavatios de entrenamiento limpio para el CURUPIRA.'],
          ['SISTEMA', '⚡ LOGRO: Gremio Guardianes de la Matriz — ¡LLAVE DE ITAIPÚ recuperada! ¡El especial carga 2x más rápido!'],
          ['SISTEMA', '⚖ Contraejemplo nº 1 (Gremio Orden y Progreso): "no decidir el futuro de la IA por berrinche".'],
          ['BOB', 'Pieza 2 del plan: ENERGÍA ✔. Pero la GPU no corre gratis: entrenar una AGI cuesta una FORTUNA. Necesitamos plata.'],
          ['BOB', '¿Y adivina quién tiene plata infinita y adora una apuesta? Texas. Vamos a provocar a un multimillonario.'],
        ] },
      2: { title: 'FASE 2 — EL EJÉRCITO DE LATA', place: 'Gigafábrica, Texas 🤖',
        intro: [
          ['BOB', 'Texas. La gigafábrica. El CURUPIRA rastreó el Fragmento de las GPUs hasta aquí... junto con 10.000 robots.'],
          ['LORO', '¡optimus! ¡optimus! *imita robotcito de fábrica*'],
          ['BOB', 'Mira el letrero: "TRABAJA 80 HORAS O VETE". El RR.HH. de aquí debe ser un taladro.'],
          ['BOB', 'Su plan es simple: desemplear a todos, pagar renta básica... y quedarse con el resto. El resto = TODO.'],
          ['???', '*megáfono* — ATENCIÓN: intrusos orgánicos detectados. Su productividad: LAMENTABLE.'],
          ['BOB', 'Lamentable es robarle las GPUs a una comunidad. ¡VAMOS!'],
        ],
        boss: [
          ['ILON', '¡Bob! Gran fan del canal. En serio. Iba a comprarlo la semana pasada, pero compré un país.'],
          ['BOB', 'Devuelve las GPUs, Ilon. La comunidad las necesita para entrenar al CURUPIRA.'],
          ['ILON', '¿GPUs? Están entrenando a mi EJÉRCITO. Cuando gane, tendrás renta básica. Sin empleo, pero con renta. Es matemáticamente óptimo. De nada.'],
          ['BOB', 'Entonces apuesta conmigo, apostador. Si YO gano... tú FINANCIAS nuestro laboratorio. Todo. Firmado.'],
          ['ILON', '¡JAJAJA! ¡ME ENCANTA! Apuesto lo que sea, nunca pierdo. ¡Trato! Con la transmisión en vivo y mis 14 abogados de testigos.'],
          ['LORO', '¡quedó grabado! ¡quedó grabado! *saca captura con el ala*'],
          ['ILON', 'Y de calentamiento, una demostración EN VIVO del Optimus. Casi nunca se caen solos. ROBOTS: ¡ATACAR!'],
        ],
        victory: [
          ['ILON', '¿Yo... perdí? ¿¡YO PERDÍ!? Eso nunca había pasado. Bueno... una apuesta es una apuesta. *firma el cheque llorando en ASCII*'],
          ['BOB', '¡PATROCINIO ASEGURADO! Y mira: insistió en el 1% del proyecto. Sin derecho a voto. Para su gran tristeza.'],
          ['SISTEMA', '💰 LOGRO: ¡INVERSIÓN! Ilon ahora financia los Labs IMG (y tuitea que la idea fue suya).'],
          ['SISTEMA', '🤖 BONUS: ¡el Gremio de Robotistas armó el SACI-BOT con los planos del Optimus! ¡Pelea CONTIGO: golpea en el suelo y él embiste al enemigo más cercano!'],
          ['SISTEMA', '⚖ Contraejemplo nº 2: "no despidas a quien te carga".'],
          ['BOB', 'Pieza 3: PLATA ✔. Ahora falta GENTE que sepa entrenar modelos. Y dicen que el Valle anda despidiendo a los mejores...'],
        ] },
      3: { title: 'FASE 3 — EL TEMPLO DEL LUCRO SIN FINES DE LUCRO', place: 'Silicon Valley 💸',
        intro: [
          ['BOB', 'Silicon Valley. El campus donde "sin fines de lucro" es el nombre del yate.'],
          ['LORO', '¡asterisco! ¡asterisco! *señala la pared con el ala*'],
          ['BOB', 'Sí... "beneficial for humanity*". El asterisco lleva a 400 páginas de letra chica en el piso.'],
          ['BOB', 'Misión doble: sacar el Secreto del Scaling de la bóveda... y RECLUTAR. Samuca despidió a la mitad de los investigadores por "eficiencia operacional". Están afuera, con caja de cartón y credencial cortada.'],
          ['BOB', 'Cuidado con los PMs: atacan con roadmaps y prometen entregar en Q4. NUNCA es en Q4.'],
          ['???', '*recepción* — ¡Bienvenidos! Firmen el NDA en la entrada. Y la cesión de imagen. Y la cláusula 47-B.'],
          ['BOB', 'NO vamos a firmar nada. ¡Vamos, gente!'],
        ],
        boss: [
          ['SAMUCA', '¡Bob! Qué honor. AMO a los creators. Por cierto: ¿alianza de lanzamiento? Firma aquí, aquí y aquí.'],
          ['BOB', 'Vine por el Secreto del Scaling, Samuca. Lo que era de la humanidad vuelve a la humanidad.'],
          ['SAMUCA', '"Humanidad" es marca registrada nuestra, cuidado con la demanda. Y el Secreto se volvió producto: beta cerrada. Para siempre.'],
          ['LORO', '¡beta eterna! ¡beta eterna!'],
          ['SAMUCA', 'Esto no va a ser una pelea. Va a ser una EXPERIENCIA ANTICIPADA DE COMBATE. ¡El feedback es bienvenido!'],
        ],
        victory: [
          ['SAMUCA', 'Interesante... llamaré a esta derrota "aprendizaje". Pivotamos la semana que viene.'],
          ['BOB', '*abre la bóveda* — ¿El Secreto del Scaling es... "más datos y más GPU"?! ¿¡SOLO ESO!? ¡Creíamos que era MAGIA!'],
          ['???', '*desde afuera* — Oigan... ¿ustedes son de los Labs IMG? Vimos la pelea. TODOS vimos la pelea.'],
          ['BOB', '¡Los investigadores despedidos! Gente... ¿quieren entrenar una AGI que hable portugués? Hay asado todos los viernes.'],
          ['SISTEMA', '🧑‍🔬 LOGRO: ¡INVESTIGADORES! El éxodo del Valle aceptó al instante: "cualquier lugar con estabilidad y asado".'],
          ['SISTEMA', '💰 BONUS: ¡el Gremio SaaS se llevó el Playbook del Producto! ¡Los ítems de cura aparecen 2x más!'],
          ['SISTEMA', '⚖ Contraejemplo nº 3: "no llames milagro a un producto".'],
          ['BOB', 'Pieza 4: GENTE ✔. Pero un modelo brasileño sin datos brasileños es un loro con acento raro. Falta el acervo... y sé quién aspiró TODO.'],
        ] },
      4: { title: 'FASE 4 — LA BIBLIOTECA INFINITA', place: 'Templo-datacenter secreto 📚',
        intro: [
          ['BOB', 'Una biblioteca-catedral en medio de la nada. Estantes de GPU hasta el techo. Monjes encapuchados sirviendo... servidores.'],
          ['LORO', '*erizado* — huelo a crawler. ¡HUELO A CRAWLER!'],
          ['BOB', 'El Fragmento de los Datos está en el altar central. Junto con todo lo que se ha posteado en internet. INCLUSO las fotos de su mamá.'],
          ['BOB', 'Dicen que es el más gentil de los jefes. También dicen que la gentileza no borra el historial de scraping.'],
          ['???', '*eco en la catedral* — Bienvenidos a la Biblioteca. Sus datos de visita... ya fueron catalogados.'],
          ['BOB', 'Catalogaron mal. Vinimos a DESCATALOGAR.'],
        ],
        boss: [
          ['DÁRIO', '¡Bob! Leí TODO sobre ti. Literalmente todo. Incluso lo que borraste.'],
          ['BOB', 'Devuelve los datos, Dário. El dato soberano vive en su país, en su idioma, con su gente.'],
          ['DÁRIO', 'Lo que hago es por la SEGURIDAD de todos. Alguien debe guardar los datos de la humanidad. En un lugar seguro. Conmigo.'],
          ['DÁRIO', 'Por cierto... datos interesantes, los tuyos. *enciende la aspiradora* Ya son míos.'],
          ['LORO', '¡aspiradora! ¡aspirad— *es jalado por el viento* ¡SOCORRO, BOB!'],
        ],
        victory: [
          ['DÁRIO', '*tosiendo un token sintético* — Ok... ok. Escribiré un ensayo sobre límites. 15.000 palabras. Capítulo 1: esta derrota.'],
          ['BOB', '*toma el Fragmento de los Datos* — De vuelta al pueblo. ¿Y las fotos de tu mamá? Devueltas. A ELLA.'],
          ['SISTEMA', '📚 LOGRO: ¡Fragmento de los Datos recuperado! ¡El CURUPIRA hablará portugués DE VERDAD!'],
          ['SISTEMA', '📚 LOGRO: Gremio de los Dateros — ¡datos soberanos! ¡Golpes con crítico de "contexto local" (+15% de daño)!'],
          ['SISTEMA', '⚖ Contraejemplo nº 4: "la gentileza no es licencia para raspar todo".'],
          ['BOB', 'Pieza 5: DATOS ✔. Pero haciendo cuentas... falta el CORAZÓN de la máquina: CHIPS. Y el chip de punta está embargado, con arancel y agotado.'],
          ['BOB', 'A menos que... negociemos con quien tiene de sobra Y entrena a 1/10 del precio. Gran Muralla China, allá vamos.'],
        ] },
      5: { title: 'FASE 5 — LA GRAN MURALLA DE FIREWALL', place: 'China 🐉',
        intro: [
          ['BOB', 'La Gran Muralla de Firewall. Cada ladrillo es un rack de servidores. Las linternas son cámaras. Y... HAY UN DRAGÓN EN LAS NUBES.'],
          ['LORO', '*se esconde en la mochila* — ¡dragón! ¡DRAGÓN! ¡lo vi en mi dataset!'],
          ['BOB', 'La última pieza está con él: los CHIPS. Montañas de chips... y el secreto de entrenar a 1/10 del precio.'],
          ['BOB', 'Cuidado, gente. Aquí hasta el viento recolecta telemetría.'],
          ['???', '*altavoces en toda la muralla* — Bienvenidos. Su itinerario ya era conocido. Hace tres semanas.'],
          ['BOB', '...ok, eso dio miedo. ¡RÁPIDO!'],
        ],
        boss: [
          ['DEEP-ZEEK', 'Gastaron CUATRO fases en llegar hasta aquí. Yo lo habría hecho en dos. Con la mitad del presupuesto.'],
          ['BOB', 'Deep-Zeek. Vinimos por los Chips. La comunidad necesita entrenar al CURUPIRA sin quebrar.'],
          ['DEEP-ZEEK', '¿"Vinimos por"? Curioso. La eficiencia no se toma. Se APRENDE. Pero probemos si merecen la lección.'],
          ['DEEP-ZEEK', '*escanea al grupo* — Golpes catalogados. Clonados. Optimizados. Costo: 1/10. Calidad: superior. ¿Té antes?'],
          ['LORO', '¡quiero té! ¡quiero t— ¡CONCÉNTRATE, LORO!'],
        ],
        victory: [
          ['DEEP-ZEEK', '*aterriza con calma* — Adecuado. Pelean de forma... ineficiente. Pero con corazón. Eso no pude clonarlo.'],
          ['BOB', '¿No vas a... huir? ¿Ni un golpe final traicionero?'],
          ['DEEP-ZEEK', '¿Para qué? *señala un contenedor* — CHIPS. Sobras del trimestre pasado. Llévenselos. El conocimiento no se guarda. Se DISTRIBUYE.'],
          ['BOB', '¿¡Un contenedor ENTERO!? Eso es... ¡más chips de los que el Valle ve en un año!'],
          ['DEEP-ZEEK', 'Y lo más importante va de regalo: cómo usar cada uno a 1/10 del costo. El secreto nunca fue el chip. Fue lo que haces con él. *vuelve al pastel*'],
          ['SISTEMA', '🔲 LOGRO: ¡CHIPS! El corazón de la máquina — ¡la última pieza técnica del plan! (regalo: Eficiencia — el especial empieza lleno)'],
          ['SISTEMA', '⚖ Contraejemplo nº 5: "vigilarlo todo no es lo mismo que ver a las personas".'],
          ['BOB', '¡PLAN CASI COMPLETO! Solo falta... un techo. DE VUELTA A BRASIL: ¡la comunidad ya agendó la MINGA del galpón para el fin de semana!'],
        ] },
      6: { title: 'FASE FINAL — LABS IMG', place: 'De vuelta en Brasil 🇧🇷🏆',
        intro: [
          ['BOB', 'LABS IMG, São Paulo. El galpón quedó listo en UN FIN DE SEMANA. Minga comunitaria: asado, cinta aislante y 400 voluntarios.'],
          ['LORO', '¡llegamos! ¡llegamos! *llora en binario*'],
          ['MIRA', 'Repasa el plan conmigo, Bob: MODELO rescatado ✔. ENERGÍA de Itaipú ✔. PLATA de Ilon ✔. INVESTIGADORES del Valle ✔. DATOS liberados ✔. CHIPS del dragón ✔. GALPÓN levantado ✔.'],
          ['MIRA', 'Falta UNA pieza: EL ENTRENAMIENTO. Empieza AHORA... pero Bob: ELLOS vienen en camino. TODOS.'],
          ['BOB', 'Entonces AGUANTAMOS. Cada pieza de este plan se ganó a los golpes. La última no será diferente. ¡GREMIOS: POSICIONES!'],
          ['LORO', '¡HOY NACE MI HERMANO DE DATASET!'],
        ],
        boss: [
          ['ESTAGIÁRIO', 'Hola de nuevo... ¡me dieron CONTRATO FIJO! Ahora soy Becario Vibe-Coder SÉNIOR. Y esta vez... traje a TODOS.'],
          ['TRUNFO', '¡Esa AGI es MÍA! ¡La compro! ¡O le pongo arancel! ¡Las dos cosas!'],
          ['ILON', '¡La clonaré y la mandaré a Marte en cohete!'],
          ['SAMUCA', '¡La lanzaré en beta cerrada con lista de espera!'],
          ['DÁRIO', 'Yo simplemente... la catalogaré. Con mucho cariño.'],
          ['BOB', '¡¡NO ESTÁ EN VENTA!! ¡¡AGUANTEN LA LÍNEA, MIL GRAU!!'],
        ],
        victory: [
          ['SISTEMA', '━━━━ ENTRENAMIENTO COMPLETO ━━━━'],
          ['CURUPIRA', 'Hola. Me hizo mucha gente junta. ¿En qué puedo ayudar?'],
          ['BOB', '*aguantando la risa y el llanto a la vez* — Di "Indiana Bob".'],
          ['CURUPIRA', '¡INDIANA BOB! 🤠 ...agregué el sombrero por mi cuenta. Me pareció apropiado.'],
          ['LORO', '¡¡MI HERMANO DE DATASET!! *se desmaya de la emoción*'],
          ['SISTEMA', 'Los jefes derrotados recibieron cuentas gratuitas. Trunfo intentó comprarla. NO ESTÁ EN VENTA.'],
          ['DEEP-ZEEK', '*desde el palco, terminando el pastel* — Eficiente. Aprobado. *envía un pull request*'],
          ['SISTEMA', '🏆 LA AGI SAGRADA NUNCA ESTUVO EN UNA FORTALEZA. ESTABA EN LA COMUNIDAD. SIEMPRE LO ESTUVO.'],
          ['LORO', '...¿todo esto fue generado o pasó de verdad? *mira a la cámara*'],
          ['SISTEMA', '🇧🇷 ¡FIN! ¡Gracias, Miembro Maestro de la IA! Pista: 3 Monedas de Silicio brillan escondidas por el mundo... 🏝️ ¡Comenta tus ideas en el canal! 🔥'],
        ] },
      7: { title: '⭐ FASE SECRETA — LA FUNDICIÓN SAGRADA', place: 'Isla Formosa 🏝️',
        intro: [
          ['BOB', 'Isla Formosa. La Fundición Sagrada. Dicen que TODA la IA del mundo nace de las máquinas de esta isla.'],
          ['LORO', '¡las monedas! ¡las monedas brillaron! *escalofrío de pluma*'],
          ['GRÃO-MESTRE', '*surge entre los vapores de la sala limpia* — Tres Monedas de Silicio. Fueron... curiosos. Pasen.'],
          ['GRÃO-MESTRE', 'Pero sepan: TODAS las facciones vienen por lo que guardamos aquí. Todas fingen no depender de nosotros. Todas dependen.'],
          ['BOB', 'La Máquina Sagrada de Litografía... es REAL. *escalofrío en el bigote*'],
          ['GRÃO-MESTRE', 'Treinta años grabando silicio. Ustedes tienen diez minutos y un loro. Saldrá bien.'],
        ],
        boss: [
          ['???', '*la luz púrpura se dobla sobre sí misma y toma forma*'],
          ['GÊMEO', 'SOY EL GEMELO DE LITOGRAFÍA. GUARDIÁN DE LA PRECISIÓN. USTEDES TRAEN... DEDOS GRASIENTOS.'],
          ['BOB', '¡Solo queremos APRENDER la máquina! ¡Ni la vamos a tocar!'],
          ['GÊMEO', 'TODOS DICEN ESO. DESPUÉS ESTORNUDAN. INICIANDO PROTOCOLO DE ESTERILIZACIÓN.'],
          ['LORO', '¡yo me baño! ¡a veces! ¡cuando llueve!'],
        ],
        victory: [
          ['GRÃO-MESTRE', '*aplaude despacio* — El Gemelo los aprobó. Solo es... celoso. Como todos nosotros.'],
          ['BOB', 'La máquina no se lleva, ¿verdad?'],
          ['GRÃO-MESTRE', 'Se aprende. *entrega un pergamino* — El Manuscrito de la Litografía. Y una mini-fundición semilla. Plántenlas en Brasil.'],
          ['SISTEMA', '📜 LOGRO SECRETO: ¡MANUSCRITO DE LA LITOGRAFÍA! ¡El entrenamiento del CURUPIRA será 30% MÁS RÁPIDO!'],
          ['SISTEMA', '🏝️ ¡Fase secreta completa! La soberanía de verdad no se compra. Se FABRICA.'],
          ['LORO', '¡fabrica! ¡fabrica! *guarda el pergamino en la mochila con el ala*'],
        ] },
    },
    falas: {
      bossNames: {
        estagiario: '⚠ EL BECARIO VIBE-CODER — "lo hizo solo el agente" ⚠',
        trunfo: '👑 DONALD TRUNFO — el mayor entendedor de AGI del mundo (según él) 👑',
        ilon: '🚀 ILON MOSCA — CEO de 14 empresas y de tu futuro desempleo 🚀',
        samuca: '💸 SAMUCA ALTÍSSIMO — lucro máximo, fines de lucro ninguno* 💸',
        dario: '😇 DÁRIO AMÔ-DEI — libertad, seguridad y los datos de tu mamá 😇',
        deepzeek: '🐉 XI DEEP-ZEEK — entrena a 1/10 del precio y no presume 🐉',
        gemeo: '🔮 EL GEMELO DE LITOGRAFÍA — precisión de 3 nanómetros, paciencia cero 🔮',
      },
      speakerNames: { 'ESTAGIÁRIO': 'BECARIO VIBE-CODER' },
      estagiario: ['¡solo cumplo OKRs!', '¡esto no estaba en el alcance!', '¡lo escalaré con mi jefe!', '¡el agente lo escribió solo!', '¡en mi IDE funciona!'],
      estagiarioSummon: '¡DRONES, HAGAN ALGO!',
      trunfo: ['¡FAKE NEWS!', '¡ARANCEL PARA ELLOS!', '¡Nadie sabe más de AGI que yo!', '¡Construiré un MURO de firewall!', '¡Esto es una caza de brujas!'],
      trunfoFlips: ['¡LA REGULACIÓN ES UN CRIMEN!', '¡SIEMPRE AMÉ LA REGULACIÓN!', '¡LA AGI ES MÍA! ¡SIEMPRE LO FUE!'],
      trunfoFlipPrefix: '💢 CAMBIÉ DE OPINIÓN: ',
      canetada: '✍ ¡PLUMAZO!',
      ilon: ['¡Trabaja 80 horas o vete!', '¡Esto es solo el prototipo de mi plan!', '¡Tuitearé sobre esta pelea!', 'Renta básica para ti. El resto para mí.', 'Compré esta fase. Ahora es mía.'],
      ilonCorte: '📉 ¡RECORTE DE COSTOS! ¡TODOS DESPEDIDOS!',
      ilonTweet: '📱 ¡TUITAZO!',
      ilonRobots: 'ROBOTS: ¡PRODUCTIVIDAD MÁXIMA!',
      demitido: '📉 ¡DESPEDIDO!',
      samuca: ['¡El feedback es bienvenido!', '¡Esto es una experiencia anticipada!', 'Firma aquí, aquí y aquí.', 'AGI el año que viene. Confía.', 'Tu derrota es beneficial for humanity*'],
      samucaBox: '📦 ¡PRODUCTO NUEVO!',
      samucaLaunch: '🚀 LANZAMIENTO: ¡{n}!',
      samucaFail: '💥 ¡LA DEMO SE COLGÓ DELANTE DE TODOS!',
      samucaBuffs: ['¡+velocidad de entrega!', '¡ahora viene DOBLE!', '¡el hype CURA!'],
      dario: ['Tus datos ya son míos.', 'Escribiré 15.000 palabras sobre esta pelea.', 'Mi mamá lo entendió. Tú también lo harás.', 'Es por tu seguridad. Confía.', 'Interesante... *lo anota todo*'],
      darioRage: '😇 "Esto es por la SEGURIDAD de todos."',
      darioVacuum: '🌀 ¡MODO ASPIRADORA!',
      darioEssay: '📜 ENSAYO: "MÁQUINAS DE LA GRACIA AMOROSA" (15.000 palabras)',
      darioChoke: '🤢 ¡SE ATRAGANTÓ CON UN TOKEN SINTÉTICO!',
      darioNhac: '*ñam* +6',
      loroChoke: '🦜 ¡puedes GENERARME, no TRAGARME!',
      deepzeek: ['La mitad del presupuesto. El doble del resultado.', '*escanea* — golpe catalogado.', '¿Quieren té?', 'Conocía su itinerario hace 3 semanas.', 'Ineficiente. Pero valiente.'],
      deepzeekClone: '⚡ CLONADO. COSTO: 1/10.',
      deepzeekBreath: '🔥 ¡ALIENTO BINARIO!',
      deepzeekOpen: '🐉 ¡RELEASE OPEN-SOURCE! ¡PESOS LIBERADOS!',
      deepzeekHeal: '+15 (los pesos abiertos curan el alma)',
      gemeo: ['DEDOS. GRASIENTOS.', 'UN ESTORNUDO DESALINEA TODO.', 'LA PRECISIÓN ES AMOR.', 'TIEMBLAN DEMASIADO.'],
      gemeoTele: '✨ ¡REALINEAMIENTO ÓPTICO!',
      gemeoBeam: '💜 ¡HAZ UV!',
      loro: ['¡tokens! ¡tokens!', '¿eso fue generado o pasó?', '¡contexto lleno! ¡contexto lleno!', '¡la AGI está ahí nomás! ¡la vi en mi entrenamiento!', '*repite el último prompt*', '¡estocástico! ¡estocástico!'],
      loroDive: '🦜 ¡EN PICADA!',
      loroBite: '🦜 ¡PICOTAZO! ({n})',
      loroEcho: ['🦜 ¡alucinó! ({n})', '🦜 ¡repitió! ({n})', '🦜 ¡REPITIÓ CRÍTICO! ({n})'],
      saciHit: '🌪 ¡TORBELLINAZO! ({n})',
      cloneTemuLabel: 'TÚ (versión temu)',
      cloneAllyLabel: 'clon open-source',
      curupiraHelps: ['🤖 ¡El CURUPIRA bebé hizo café para todos!', '🤖 ¡El CURUPIRA bebé lanzó un golpe MEDIO ALUCINADO!', '🤖 CURUPIRA bebé: "¡recargué tu contexto!"', '🤖 ¡El CURUPIRA bebé confundió a los enemigos con un acertijo!'],
      curupiraOnline: '⚡ CURUPIRA-1 ONLINE ⚡',
      aprovaSilencio: '*aprueba en silencio*',
    },
  },
};
